import Person, { IPerson } from 'components/Person';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useQuery } from 'react-query';
import styles from 'styles/Home.module.css';

const Home: NextPage = () => {
  const { data, isLoading } = useQuery('test', () =>
    fetch('https://swapi.dev/api/people').then((res) => res.json())
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {isLoading ? (
          <h4 className={styles.title}>loading...</h4>
        ) : (
          <div className={styles.grid}>
            {data?.results?.map(({ name, hair_color, eye_color }: IPerson) => (
              <Person
                key={`${name}_${hair_color}`}
                name={name}
                hair_color={hair_color}
                eye_color={eye_color}
              />
            ))}
          </div>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
